/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package edu.lee

import spock.lang.Specification

class CalculationServiceTest extends Specification {
    def "add numbers"() {
        setup:
        def service = new CalculationService()

        when:
        def result = service.add(1, 2)

        then:
        result == 3
    }
}
