/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package edu.lee

import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new PreMainAgent()

//        when:
//        def result = lib.someLibraryMethod()

//        then:
//        result == true
    }
}
