/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

public class App {
    public static void main(String[] args) {
        CalculationService service = new CalculationService();
        System.out.println("1 + 2 = " + service.add(1, 2));
    }
}
