/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTwoTest {
    @Test void testSomeLibraryTwoMethod() {
        LibraryTwo classUnderTest = new LibraryTwo();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
