/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        LibraryOne one = new LibraryOne();
        assertTrue(one.someLibraryMethod());

        LibraryTwo two = new LibraryTwo();
        assertTrue(two.someLibraryMethod());
    }
}
