/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.*;

class DynamicClassTest {
    @Test void testDynamicPojoBean() throws Exception {
        File javaFile = new File(DynamicClassTest.class.getClassLoader().getResource("./PojoBean.txt").toURI());
        String source = FileUtils.readFileToString(javaFile, "utf-8");
        System.out.println("loaded java source =====================");
        System.out.println(source);
        System.out.println("========================================");

        Object bean = ClassFactory.createClassObject("edu.lee.PojoBean", source);
        Method method = bean.getClass().getMethod("getId");
        int id = (int)method.invoke(bean);

        method = bean.getClass().getMethod("getName");
        String name = (String)method.invoke(bean);

        assertAll(
                () -> assertEquals(1, id),
                () -> assertEquals("lee", name)

        );
    }

//    @Test void test() throws Exception {
//        DynamicClassTest dct = (DynamicClassTest)Class.forName("edu.lee.DynamicClassTest").getDeclaredConstructor().newInstance();
//        System.out.println(dct.toString());
//    }
}
