/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.instrument.Instrumentation;
import java.security.ProtectionDomain;

public class PreMainAgent {

    public static void premain(String agentArgs, Instrumentation inst){
        System.out.println("agentArgs : " + agentArgs);
        inst.addTransformer(TransformerFactory.createTransformer(agentArgs), true);
    }

}
