/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryOneTest {
    @Test void testSomeLibraryOneMethod() {
        LibraryOne classUnderTest = new LibraryOne();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
